version: '3'
services:

 ##########################################################
  rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:3.7.14-management-alpine
    volumes:
      - ./mq_data:/var/lib/rabbitmq/mnesia
    ports:
      - "15672:15672"
      - "5672:5672" 

    environment:
      RABBITMQ_DEFAULT_USER: JumiaUser
      RABBITMQ_DEFAULT_PASS: JumiaPass
      RABBITMQ_DEFAULT_VHOST: JumiaVirtualHost
      
  ##########################################################
  
  elasticsearch:
    container_name: ElasticSearch    
    image: elasticsearch:7.0.0
    environment: 
      - discovery.type=single-nodecd 
      - transport.host=0.0.0.0
      - cluster.name="elastic_stack_logging"
      - node.name="elastic_stack_logging_data"
      - discovery.zen.minimum_master_nodes=1
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
    volumes: 
      - ./elasticsearch_data:/usr/share/elasticsearch/data   
      #- ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml   
    ports:
      - "9200:9200"
      - "9300:9300"

    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 5     

    
  ##########################################################
  
  logstash:
    container_name: LogStash    
    image: logstash:7.0.0
    volumes:
      - ./product.logstash.conf:/config/product.logstash.conf      
    links:
      - rabbitmq
      - elasticsearch
    command: logstash -f /config/product.logstash.conf  
    depends_on:
      - rabbitmq
      - elasticsearch

##########################################################
      
  app1:
    container_name: LoggerApp
    image: logger-app-build:1
    ports: 
      - 8180:8080
    depends_on:
      - logstash


  app2:
    container_name: LoggerSdesApp
    image: logger-sdes-app-build:1
    ports: 
      - 8280:8080
    depends_on:
      - logstash


volumes:
  mq_data:
  elasticsearch_data:

    