version: '3'
services:

 ##########################################################
  rabbitmq:
    container_name: RabbitMQ
    hostname: rabbitmq
    image: rabbitmq:3.7.14-management-alpine
    volumes:
      - ./data/mq_data:/var/lib/rabbitmq/mnesia
    ports:
      - "15672:15672"
      - "5672:5672" 
    networks: 
      - log
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: virtualHost

  ##########################################################
  elasticsearch:
    container_name: ElasticSearch    
    image: elasticsearch:6.7.1
    environment: 
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      #- cluster.name="elastic_stack_logging"
      #- discovery.zen.minimum_master_nodes=1
    volumes: 
      - ./data/elasticsearch_data:/usr/share/elasticsearch/data   
    ports:
      - "9200:9200"
      - "9300:9300"
    networks: 
      - log

  ###########################################################
  logstash:
    container_name: LogStash    
    image: logstash:6.7.1
    volumes:
      - ./config/logstash:/config
    command: logstash --path.config /config
    depends_on:
      - rabbitmq
      - elasticsearch
    networks: 
      - log

  # app1:
  #   container_name: LoggerApp
  #   image: loggerapp:1
  #   ports: 
  #     - 8180:8080
  #   depends_on: 
  #     - rabbitmq
  #     - elasticsearch
  #   networks: 
  #     - log

  app2:
    container_name: LoggerAppData
    image: loggerappdata:1
    ports: 
      - 8280:8080      
    depends_on: 
      - rabbitmq
      - elasticsearch
    networks: 
      - log

networks: 
  log:
    driver: bridge


