version: '3'
services:

 ##########################################################
  rabbitmq:
    container_name: RabbitMQ
    image: rabbitmq:3.7.14-management-alpine
    volumes:
      - ./mq_data:/var/lib/rabbitmq/mnesia
    ports:
      - "15672:15672"
      - "5672:5672" 
    networks:
      - log
    environment:
      RABBITMQ_DEFAULT_USER: JumiaUser
      RABBITMQ_DEFAULT_PASS: JumiaPass
      RABBITMQ_DEFAULT_VHOST: JumiaVirtualHost
  ##########################################################
  elasticsearch:
    container_name: ElasticSearch    
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.0.0
    environment: 
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - network.host=0.0.0.0
      - cluster.name="elastic_stack_logging"
      - node.name="elastic_stack_logging_data"
      - discovery.zen.minimum_master_nodes=1
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
    volumes: 
      - ./elasticsearch_data:/usr/share/elasticsearch/data      
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 5     
    networks:
      - log
  ##########################################################
  
  ##########################################################
  logstash:
    container_name: LogStash    
    image: docker.elastic.co/logstash/logstash-oss:7.0.0
    volumes:
      - ./product.logstash.conf:/config/product.logstash.conf      
    links:
      - rabbitmq:AMQPServer
      - elasticsearch:elasticsearch
    networks:
      - log    
    command: logstash -f /config/product.logstash.conf  
    depends_on:
      - rabbitmq
      - elasticsearch

volumes:
  mq_data:
  elasticsearch_data:

networks:
  log:
    driver: bridge