version: '3'
services:

 ##########################################################
  rabbitmq:
    container_name: RabbitMQ
    hostname: rabbitmq
    image: rabbitmq:3.7.14-management-alpine
    volumes:
      - ./mq_data:/var/lib/rabbitmq/mnesia
    ports:
      - "15672:15672"
      - "5672:5672" 
    environment:
      RABBITMQ_DEFAULT_USER: JumiaUser
      RABBITMQ_DEFAULT_PASS: JumiaPass
      RABBITMQ_DEFAULT_VHOST: JumiaVirtualHost

  ##########################################################

  elasticsearch:
    container_name: ElasticSearch    
    image: elasticsearch:7.0.0
    environment: 
      - discovery.type=single-node
      # - transport.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      #- cluster.name="elastic_stack_logging"
      #- discovery.zen.minimum_master_nodes=1
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
    volumes: 
      - ./elasticsearch_data:/usr/share/elasticsearch/data   
      #- ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml   
    ports:
      - "9200:9200"
      - "9300:9300"

  # ##########################################################

  logstash:
    container_name: LogStash    
    image: logstash:7.0.0
    volumes:
      - ./config/logstash:/config
    #command: logstash -f /config/product.logstash.conf  
    command: logstash --path.config /config
    depends_on:
      - rabbitmq
      - elasticsearch

  # app1:
  #   container_name: LoggerApp
  #   image: loggerapp:1
  #   ports: 
  #     - 8180:8080
  #   depends_on: 
  #     - rabbitmq
  #     - elasticsearch
  #     - logstash

  # app2:
  #   container_name: LoggerSdesApp
  #   image: loggerappsdes:1
  #   ports: 
  #     - 8280:8280

  

volumes:
  mq_data:
  elasticsearch_data:
